In [111]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

melbourne_file_path = '../Melborn House Price Prediction/melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path)
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [112]:
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [113]:
y = melbourne_data.Price
features = ['Rooms', 'Landsize', 'Bathroom', 'Lattitude', 'Longtitude']
X = melbourne_data[features]
X.head(n=50)

    Rooms  Landsize  Bathroom  Lattitude  Longtitude
0       2     202.0       1.0   -37.7996    144.9984
1       2     156.0       1.0   -37.8079    144.9934
2       3     134.0       2.0   -37.8093    144.9944
3       3      94.0       2.0   -37.7969    144.9969
4       4     120.0       1.0   -37.8072    144.9941
5       2     181.0       1.0   -37.8041    144.9953
6       3     245.0       2.0   -37.8024    144.9993
7       2     256.0       1.0   -37.8060    144.9954
8       1       0.0       1.0   -37.8008    144.9973
9       2     220.0       1.0   -37.8010    144.9989
10      2       0.0       2.0   -37.8110    145.0067
11      3     214.0       2.0   -37.8085    144.9964
12      2       0.0       2.0   -37.8078    144.9965
13      2     195.0       1.0   -37.8084    144.9973
14      1       0.0       1.0   -37.8016    144.9988
15      2     238.0       1.0   -37.8090    144.9976
16      3     113.0       2.0   -37.8056    144.9930
17      3     138.0       1.0   -37.8021    144.9965
18      3     183.0       1.0   -37.8022    144.9975
19      2     150.0       1.0   -37.8011    145.0004
20      4     780.0       2.0   -37.8073    144.9952
21      3       0.0       2.0   -37.8093    144.9959
22      3    4290.0       2.0   -37.8078    144.9965
23      2       0.0       1.0   -37.8015    144.9972
24      2     124.0       2.0   -37.8079    144.9977
25      2     147.0       1.0   -37.8080    144.9940
26      1       0.0       1.0   -37.8016    144.9988
27      3     166.0       3.0   -37.8017    145.0001
28      1       0.0       1.0   -37.8078    144.9965
29      2      98.0       2.0   -37.8005    144.9952
30      4       0.0       3.0   -37.7994    144.9965
31      3     147.0       2.0   -37.8050    144.9943
32      3     168.0       1.0   -37.8007    144.9958
33      1       0.0       1.0   -37.8055    144.9961
34      2     162.0       1.0   -37.8016    144.9956
35      3     120.0       2.0   -37.8022    144.9954
36      2     182.0       1.0   -37.8021    144.9976
37      2     172.0       1.0   -37.8086    144.9946
38      3     303.0       2.0   -37.7180    144.8780
39      3       0.0       2.0   -37.7203    144.8755
40      3       0.0       2.0   -37.7203    144.8755
41      2     272.0       1.0   -37.7294    144.8880
42      3     239.0       2.0   -37.7218    144.8837
43      3     290.0       1.0   -37.7273    144.8744
44      2     168.0       1.0   -37.7215    144.8864
45      3     620.0       1.0   -37.7173    144.8872
46      4     597.0       1.0   -37.7259    144.8792
47      6     976.0       3.0   -37.7239    144.8735
48      2     110.0       1.0   -37.7216    144.8710
49      2     141.0       1.0   -37.7298    144.8883

In [114]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=1)

In [154]:
#Randomforest model
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor()
rf_model.fit(train_X, train_y)
rf_val_predictions = rf_model.predict(val_X)
rf_val_mae = mean_absolute_error(rf_val_predictions, val_y)

print("Validation MAE for Random Forest Model: {:,.0f}".format(rf_val_mae))

Validation MAE for Random Forest Model: 180,831

In [117]:
#LinearRegression model
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(train_X, train_y)
lr_val_predictions = lr_model.predict(val_X)
lr_val_mae = mean_absolute_error(lr_val_predictions, val_y)

print("Validation MAE for LinearRegressiont Model: {:,.0f}".format(lr_val_mae))

Validation MAE for LinearRegressiont Model: 359,778

In [127]:
def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    lr_model = LinearRegression()
    lr_model.fit(train_X, train_y)
    lr_val_predictions = lr_model.predict(val_X)
    lr_val_mae = mean_absolute_error(val_y, lr_val_predictions)
    return(lr_val_mae)

for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  359778
Max leaf nodes: 50  		 Mean Absolute Error:  359778
Max leaf nodes: 500  		 Mean Absolute Error:  359778
Max leaf nodes: 5000  		 Mean Absolute Error:  359778

Linear Regression is not a tree-based model. It works by finding the best-fitting linear relationship between the features and the target variable. For Linear Regression, there isn't a direct equivalent hyperparameter like max_leaf_nodes to tune its complexity in the same way tree-based models are tuned. Linear Regression's complexity is primarily determined by the number of features in your dataset.

In [158]:
import pickle

filename = 'melbourne_house_price_model.pkl'  # Choose a filename

# Save the model to a file
with open(filename, 'wb') as file:
    pickle.dump(rf_model, file)  # Use rf_model instead of best_rf_model

print(f"Model saved to {filename}")

Model saved to melbourne_house_price_model.pkl

In [160]:
import pickle

filename = 'melbourne_house_price_model.pkl'  # The same filename you used to save

# Load the model from the file
with open(filename, 'rb') as file:
    loaded_rf_model = pickle.load(file)

print(f"Model loaded from {filename}")

Model loaded from melbourne_house_price_model.pkl

In [170]:
import pandas as pd

# Assume 'new_data' is a Pandas DataFrame with the features of the new houses
# Example:
new_data = pd.DataFrame({
    'Rooms': [3, 4, 2],
    'Landsize': [200, 350, 180],
    'Bathroom': [2, 2, 1],
    'Lattitude': [-37.7969, -37.7323, -38.7969], 
    'Longtitude': [144.9966, 144.9956, 144.9987]
})

# Use the loaded model to predict prices
new_predictions = loaded_rf_model.predict(new_data) # This part stays the same (assuming you load into loaded_rf_model)

print("Price predictions for the new houses:")
print(new_predictions)

Price predictions for the new houses:
[1369005.    902010.74  828835.  ]